### ISSUE TITLE
auxiliary files not translated

### ISSUE THREAD

**Issue by raynamharris** [carpentries/git-novice-es-archive#14]
I noticed that many of the pages in the top level directory are not translated, such as:
- [ ] README.md
- [ ] setup.md
- [ ] index.md
- [ ] reference.md

Is there a plan to translate these?

**Comment by orchid00** [comment]
Thanks @raynamharris I think we should.
I would like to hear from @map0logo first, because I am not completely sure how the new lesson will look like, I am guessing it will have its own repo and then for sure we will need these files too.
But if we do that we first need to know where to put those translations, as those are in the main folder, we will need to override them? What are your thoughts/ suggestions @raynamharris ?

**Comment by olemis** [comment]
Hello

In olemis/git-novice I have a Spanish translation for index.md file . May I continue with the other files or switch to olemis/shell-novice instead ?

**Comment by olemis** [comment]
I'm interested in Python novice Gapminder . Are there any pending translations there ?

**Comment by orchid00** [comment]
Olemis, please continue to the other files on the git lesson (send PR please). We haven't started the Python novice gapminder yet, but that will be the next.
